// src/js/modules/api.js

/**
 * Parses the generated search query to separate recognized parameters from the main search term.
 * @param {string} query - The full search query string generated by the user.
 * @returns {object} An object containing parsed parameters.
 */
function parseAdvancedSearchParams(query) {
    const params = {
        srsearch: query,
        srincategory: '',
        deepcategory: '',
        srhastemplate: '',
        srprefix: '',
        srincontent: '', // Corresponds to insource
        srfiletype: ''
    };

    let currentQuery = query; // Use a distinct variable to track the evolving query string

    const definitions = {
        srincategory: { regex: /incategory:("([^"]*?)"|([^\s]+))/gi, separator: '|' }, // Global regex
        deepcategory: { regex: /deepcat:("([^"]*?)"|([^\s]+))/gi },
        srhastemplate: { regex: /hastemplate:("([^"]*?)"|([^\s]+))/gi },
        srprefix: { regex: /prefix:("([^"]*?)"|([^\s]+))/gi },
        srincontent: { regex: /insource:("([^"]*?)"|([^\s]+))/gi },
        srfiletype: { regex: /filetype:("([^"]*?)"|([^\s]+))/gi }
    };

    for (const paramKey in definitions) {
        const { regex, separator } = definitions[paramKey];
        let values = [];

        // Find all matches for the current parameter type
        const matches = [...currentQuery.matchAll(regex)]; // Get all matches

        matches.forEach(match => {
            const value = match[2] || match[3]; // Quoted or unquoted value
            if (value) {
                values.push(value);
            }
        });

        if (values.length > 0) {
            params[paramKey] = values.join(separator || ' '); // Join with separator or space
        }

        // Remove ALL occurrences of this parameter from the query string
        currentQuery = currentQuery.replace(regex, '').trim();
    }

    params.srsearch = currentQuery.trim(); // The remainder is the core search string

    return params;
}

/**
 * Generic helper for Wikipedia API fetches with error handling.
 */
async function fetchWikiData(lang, params) {
    const endpoint = `https://${lang}.wikipedia.org/w/api.php`;
    const queryParams = new URLSearchParams({
        format: 'json',
        origin: '*',
        ...params
    });
    
    try {
        const response = await fetch(`${endpoint}?${queryParams}`);
        if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
        return await response.json();
    } catch (error) {
        console.error("Wikipedia API fetch error:", error);
        return null;
    }
}

/**
 * Performs a search on the Wikipedia API.
 */
export async function performWikipediaSearch(query, lang = 'de', limit = 10) {
    return await fetchWikiData(lang, {
        action: 'query',
        list: 'search',
        srsearch: query,
        srlimit: limit,
        prop: 'pageimages',
        piprop: 'thumbnail',
        pithumbsize: 150
    });
}

/**
 * Fetches additional info (like images) for specific titles.
 */
export async function fetchArticlesInfo(titles, lang = 'de') {
    return await fetchWikiData(lang, {
        action: 'query',
        titles: titles.join('|'),
        prop: 'pageimages',
        piprop: 'thumbnail',
        pithumbsize: 150
    });
}

/**
 * Fetches a brief summary for a given article title.
 */
export async function fetchArticleSummary(title, lang) {
    const data = await fetchWikiData(lang, {
        action: 'query',
        prop: 'extracts',
        exsentences: 10,
        exintro: true,
        explaintext: true,
        titles: title
    });

    if (!data) return "Summary could not be retrieved.";
    
    const pages = data.query.pages;
    const pageId = Object.keys(pages)[0];
    if (pageId === "-1" || !pages[pageId].extract) {
        return "No summary available.";
    }
    return pages[pageId].extract;
}

/**
 * Fetches summaries for multiple articles in one batch.
 */
export async function fetchArticlesSummaries(titles, lang) {
    const data = await fetchWikiData(lang, {
        action: 'query',
        prop: 'extracts',
        exsentences: 3, // Reduced for batch to keep payload small
        exintro: true,
        explaintext: true,
        titles: titles.join('|'),
        exlimit: titles.length
    });

    if (!data || !data.query || !data.query.pages) return {};
    return data.query.pages;
}

/**
 * Fetches categories for multiple articles in batches.
 */
export async function fetchArticlesCategories(titles, lang, onProgress) {
    const batchSize = 50;
    const allPages = {};

    for (let i = 0; i < titles.length; i += batchSize) {
        const batchTitles = titles.slice(i, i + batchSize);
        if (onProgress) onProgress(i, titles.length);
        
        const data = await fetchWikiData(lang, {
            action: 'query',
            titles: batchTitles.join('|'),
            prop: 'categories',
            cllimit: 50,
            clshow: '!hidden'
        });

        if (data && data.query && data.query.pages) {
            Object.assign(allPages, data.query.pages);
        }
    }
    return allPages;
}
